Traceback (most recent call last):
  File "/Users/nordin/opt/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/nordin/opt/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/nordin/opt/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/nordin/opt/anaconda3/envs/jupyterbook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/nordin/opt/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/nordin/opt/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/nordin/opt/anaconda3/envs/jupyterbook/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
traffic_violations['Accident'] = traffic_violations['Accident'].map({'Yes': 1, 'No': 0})
traffic_violations['Belts'] = traffic_violations['Belts'].map({'Yes': 1, 'No': 0})
traffic_violations['Personal Injury'] = traffic_violations['Personal Injury'].map({'Yes': 1, 'No': 0})
traffic_violations['Fatal'] = traffic_violations['Fatal'].map({'Yes': 1, 'No': 0})
traffic_violations['Alcohol'] = traffic_violations['Alcohol'].map({'Yes': 1, 'No': 0})
traffic_violations['Work Zone'] = traffic_violations['Work Zone'].map({'Yes': 1, 'No': 0})
traffic_violations['Contributed To Accident'] = traffic_violations['Contributed To Accident'].map({'Yes': 1, 'No': 0})

df_accidents['Astronomical_Twilight'] = df_accidents['Astronomical_Twilight'].map({'Day' : 1, 'Night' : 0})
df_accidents['Civil_Twilight'] = df_accidents['Civil_Twilight'].map({'Day' : 1, 'Night' : 0})
df_accidents['Nautical_Twilight'] = df_accidents['Nautical_Twilight'].map({'Day' : 1, 'Night' : 0})

df_accidents.corr(numeric_only = True)
traffic_violations.corr(numeric_only = True)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 9[0m
[1;32m      6[0m traffic_violations[[38;5;124m'[39m[38;5;124mWork Zone[39m[38;5;124m'[39m] [38;5;241m=[39m traffic_violations[[38;5;124m'[39m[38;5;124mWork Zone[39m[38;5;124m'[39m][38;5;241m.[39mmap({[38;5;124m'[39m[38;5;124mYes[39m[38;5;124m'[39m: [38;5;241m1[39m, [38;5;124m'[39m[38;5;124mNo[39m[38;5;124m'[39m: [38;5;241m0[39m})
[1;32m      7[0m traffic_violations[[38;5;124m'[39m[38;5;124mContributed To Accident[39m[38;5;124m'[39m] [38;5;241m=[39m traffic_violations[[38;5;124m'[39m[38;5;124mContributed To Accident[39m[38;5;124m'[39m][38;5;241m.[39mmap({[38;5;124m'[39m[38;5;124mYes[39m[38;5;124m'[39m: [38;5;241m1[39m, [38;5;124m'[39m[38;5;124mNo[39m[38;5;124m'[39m: [38;5;241m0[39m})
[0;32m----> 9[0m df_accidents[[38;5;124m'[39m[38;5;124mAstronomical_Twilight[39m[38;5;124m'[39m] [38;5;241m=[39m [43mdf_accidents[49m[[38;5;124m'[39m[38;5;124mAstronomical_Twilight[39m[38;5;124m'[39m][38;5;241m.[39mmap({[38;5;124m'[39m[38;5;124mDay[39m[38;5;124m'[39m : [38;5;241m1[39m, [38;5;124m'[39m[38;5;124mNight[39m[38;5;124m'[39m : [38;5;241m0[39m})
[1;32m     10[0m df_accidents[[38;5;124m'[39m[38;5;124mCivil_Twilight[39m[38;5;124m'[39m] [38;5;241m=[39m df_accidents[[38;5;124m'[39m[38;5;124mCivil_Twilight[39m[38;5;124m'[39m][38;5;241m.[39mmap({[38;5;124m'[39m[38;5;124mDay[39m[38;5;124m'[39m : [38;5;241m1[39m, [38;5;124m'[39m[38;5;124mNight[39m[38;5;124m'[39m : [38;5;241m0[39m})
[1;32m     11[0m df_accidents[[38;5;124m'[39m[38;5;124mNautical_Twilight[39m[38;5;124m'[39m] [38;5;241m=[39m df_accidents[[38;5;124m'[39m[38;5;124mNautical_Twilight[39m[38;5;124m'[39m][38;5;241m.[39mmap({[38;5;124m'[39m[38;5;124mDay[39m[38;5;124m'[39m : [38;5;241m1[39m, [38;5;124m'[39m[38;5;124mNight[39m[38;5;124m'[39m : [38;5;241m0[39m})

[0;31mNameError[0m: name 'df_accidents' is not defined

